# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN pnpm install --frozen-lockfile

# Copy source and build
COPY src ./src
RUN pnpm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Install production dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# Default command to run the MCP stdio server
CMD ["node", "dist/mcp.js"]
